### ISSUE TITLE
Exporter configuration via Helm Chart doesn't sync crdsToDiscover and overwriteCrdsActions options

### ISSUE THREAD

**Issue by irizzant** [port-labs/port-k8s-exporter#86]
I have deployed Exporter with Helm chart version 0.2.36 in kubernetes 1.30 with the following helm chart configuration:
```yaml
overwriteConfigurationOnRestart: true
eventListener:
  type: POLLING
configMap:
  name: config-k8s.yaml
  config:
    crdsToDiscover: ".metadata.ownerReferences[0].kind == \"CompositeResourceDefinition\" and .spec.scope == \"Namespaced\""
    overwriteCrdsActions: false
    resources:
    - kind: v1/namespaces
    .... # omitted for brevity
```
In Port this configuration translates into:
```yaml
resources:
    - kind: v1/namespaces
    .... # omitted for brevity
```

The Kubernetes ConfigMap contains the right configuration, but it's not mirrored in Port though.

This is a problem because if I manually update the kubernetes datasource in Port adding the missing configurations:
```yaml
crdsToDiscover: ".metadata.ownerReferences[0].kind == \"CompositeResourceDefinition\" and .spec.scope == \"Namespaced\""
    overwriteCrdsActions: false
```
then at the next restart of the exporter pod the configuration is lost.
On the other end, by setting `overwriteConfigurationOnRestart: true`  I loose the possibility to keep the configuration in sync with Port

**Comment by abangser** [comment]
Just adding a plus one and hopefully some helpful context. I have tried doing the same thing and I noticed in the exporter logs that I see:
```
crd.go:369] Discovering CRDs is disabled
```

I don't see any env vars or configs that can change this so I wonder if this may be the issue?

Would love to fully automate my setup with Port and this would seem to do it 🤞

**Comment by omby8888** [comment]
Hi @abangser, @irizzant ,
Thank you for reporting this issue! it has been resolved in version v0.4.5. Please update to the latest version and let us know if you encounter any further issues.

**Comment by omby8888** [comment]
Hey @abangser, iv'e now also released the helm chart 😄

**Comment by irizzant** [comment]
Hi @abangser thanks for the update, the `overwriteCrdsActions` is still not synced to the exporter configuration in Port but the `crdsToDiscover` part works fine. Can you check?

**Comment by abangser** [comment]
Heyya @irizzant, so sorry for the delayed response.

I can confirm that I can use the Helm chart to set the `crdsToDiscover` via the `configMap.config` value.

Specifically, I used:
```
# port-config.yaml
resources: []
crdsToDiscover: >-
  "mykind.myorg.io" as $crdNames | .metadata.name |  test($crdNames)

# Helm command
helm upgrade --install port-exporter port-labs/port-k8s-exporter \
  --version 0.2.37 \
  --namespace port-k8s-exporter \
  --create-namespace \
  --set stateKey=my-port-exporter \
  --set createDefaultResources=false \
  --set overwriteConfigurationOnRestart=true \
  --set secret.useExistingSecret=true \
  --set-file configMap.config=port-config.yaml
```

And with that, I saw the blueprint, integration, and self-serve actions all populate which was great 🎉 

I did however get surprised that any updates to the CM didn't seem to reflect in the UI. Once this has synced for the first time, is it expected to then update the config settings via the UI or the API? For completeness, what I saw was:
* When I update in the ConfigMap, nothing changes in how the exporter behaves or the settings visible in the UI
* When I update via the UI, the exported uses the new setting, but the CM doesn't change

Therefore, it seems like the CM is being used as a one off setup? Is that the right understanding? This seems reinforced by the docs [here](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/kubernetes/?installation-methods=argo#updating-exporter-configuration).

If my understanding is correct, I am a bit worried about config being a required field, but being also so likely to be out of date with the working value in the UI/API. I would maybe then want to just set up the integration via the API/UI and install the exporter deployment without the comprehensive details in the helm chart. But that doesn't seem to be a provided option at the moment 💭

**Comment by irizzant** [comment]
This is strange, I don't seem to have this behaviour.

**Comment by abangser** [comment]
I wouldn't be surprised if it is noob behaviour. @irizzant I have shot you over a video in the community slack in case that helps pin down the issue. And will of course update here when we figure it out!

**Comment by abangser** [comment]
OK, have had a chance to give more of a look and I have a plan to manage the configuration but the addition of the `overwriteCrdsActions` would be needed. I believe this requires adding this flag to the init config and then exposing it via the helm chart. Do you have a sense of timeline on that flag? Thanks so much for your help!

**Comment by abangser** [comment]
If it is helpful, I have this change I could open a PR with: https://github.com/port-labs/port-k8s-exporter/compare/main...abangser:port-k8s-exporter:expose-overwritecrdsaction

I know it doesn't have automated tests, but I can't figure out how to run those off the branch, so I didn't want to blindly write them. But I have managed to test this and have confirmed it works when the env var `OVERWRITE_CRDS_ACTIONS` is set.

Thanks!

**Comment by abangser** [comment]
Hi all, just curious if you got an eye on that diff I suggested around overwrites. I would love to get off my fork and support the main branch development but this is blocking for me. 

And still happy to make PR etc if helpful 😄
